version: '2'

services:
  mongodb:
    image: 'mongo:4.4'
    container_name: mongodb
    ports:
      - "27017:27017"
  nats-server:
    image: 'nats:2.1.9'
    container_name: nats
    restart: always
    ports:
      - "4222:4222"
  redis:
    image: 'redis:7.0.4'
    container_name: redis
    ports:
      - "6379:6379"